system:
  addr: 80
  reader_time_out: 20
  writer_time_out: 20
  max_params: 2

xxl:
  XXL_JOB_ADMIN_ADDRESS: 'http://xxl-job-admin.kukejs-test.svc.cluster.local/xxl-job-admin'
  XXL_JOB_APP_NAME: 'kuke-logger-test'

